/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cookie.clicker;

import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Jogo extends javax.swing.JFrame {
    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
    }
    public int counter;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1 = new cookie.clicker.Painel();
        lblPontos = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        txtPontos = new javax.swing.JTextField();
        btnResetar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mbtnSalvar = new javax.swing.JMenuItem();
        mbtnCarregar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        painel1.setImg(new ImageIcon("src/imagens/black_hole.jpg")
        );

        lblPontos.setBackground(new java.awt.Color(255, 51, 51));
        lblPontos.setForeground(new java.awt.Color(255, 255, 255));

        btnClick.setBackground(new java.awt.Color(102, 51, 0));
        btnClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cookie_JE2_BE2.jpg"))); // NOI18N
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        txtPontos.setEditable(false);
        txtPontos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPontos.setText("0");

        btnResetar.setBackground(new java.awt.Color(102, 51, 0));
        btnResetar.setText("Reset");
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPontos)
                    .addComponent(btnClick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1514, Short.MAX_VALUE))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnClick)
                .addGap(65, 65, 65)
                .addComponent(btnResetar)
                .addContainerGap(496, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        mbtnSalvar.setText("Salvar");
        mbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(mbtnSalvar);

        mbtnCarregar.setText("Carregar");
        mbtnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnCarregarActionPerformed(evt);
            }
        });
        jMenu1.add(mbtnCarregar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        counter = Integer.parseInt(txtPontos.getText());
        txtPontos.setText(Integer.toString(++counter));
    }//GEN-LAST:event_btnClickActionPerformed

    private void mbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnSalvarActionPerformed
        salvamento();
    }//GEN-LAST:event_mbtnSalvarActionPerformed

    private void mbtnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnCarregarActionPerformed
        try {
            carregar();
        } catch (IOException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mbtnCarregarActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        txtPontos.setText("0");
    }//GEN-LAST:event_btnResetarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClick;
    private javax.swing.JButton btnResetar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JMenuItem mbtnCarregar;
    private javax.swing.JMenuItem mbtnSalvar;
    private cookie.clicker.Painel painel1;
    private javax.swing.JTextField txtPontos;
    // End of variables declaration//GEN-END:variables
    
    public void salvamento(){
        try{
            FileWriter escritor = new FileWriter("src/arquivotxt/pontuacao.txt");   
            escritor.write(txtPontos.getText());
            escritor.close();
            JOptionPane.showMessageDialog(rootPane, "Arquivo salvo com sucesso");        
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possivel salvar");
        }
    }
    
    public void carregar() throws IOException{
        String arquvio = new String(Files.readAllBytes(Paths.get("src/arquivotxt/pontuacao.txt")));
        txtPontos.setText(arquvio);
    }
    
    public void carregar1(){
        try {
            String linha;
            File arquivo = new File("src/arquivotxt/pontucao.txt");
            Scanner leitor = new Scanner(arquivo);
            while (leitor.hasNextLine()) {              
                linha = leitor.nextLine();
                txtPontos.setText(linha);
            }
            leitor.close(); 
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possivel carregar o arquivo");
        }
    }
}
