/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cookie.clicker;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Jogo extends javax.swing.JFrame {
    
    public int cookieCounter;
    public int ponto;
    
    public Jogo() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1 = new cookie.clicker.Painel();
        jLabel1 = new javax.swing.JLabel();
        btnCookie = new javax.swing.JButton();
        txtPontos = new javax.swing.JTextField();
        btnResetar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtMensagem = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mbtnSalvar = new javax.swing.JMenuItem();
        mbtnCarregar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel1.setImg(new ImageIcon("src/imagens/background.png")
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cookies");

        btnCookie.setBackground(new java.awt.Color(102, 51, 0));
        btnCookie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cookie_JE2_BE2.jpg"))); // NOI18N
        btnCookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookieActionPerformed(evt);
            }
        });

        txtPontos.setEditable(false);
        txtPontos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPontos.setText("0");

        btnResetar.setBackground(new java.awt.Color(102, 51, 0));
        btnResetar.setText("Reset");
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jtxtMensagem);

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPontos)
                            .addComponent(btnCookie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(txtPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCookie)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnResetar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        mbtnSalvar.setText("Salvar");
        mbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(mbtnSalvar);

        mbtnCarregar.setText("Carregar");
        mbtnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnCarregarActionPerformed(evt);
            }
        });
        jMenu1.add(mbtnCarregar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCookieActionPerformed
        cookieCounter = Integer.parseInt(txtPontos.getText());
        txtPontos.setText(Integer.toString(++cookieCounter));
        Random random = new Random();
        ponto = random.nextInt(10)+1;
        if (cookieCounter > 50 && cookieCounter < 99) {
            txtPontos.setText(Integer.toString(ponto+cookieCounter));
        } else if (cookieCounter > 100 && cookieCounter < 999) {
            txtPontos.setText(Integer.toString(15+cookieCounter));
        } else if (cookieCounter > 1000 && cookieCounter < 10000) {
            txtPontos.setText(Integer.toString((ponto*3)+cookieCounter));
            jtxtMensagem.setText("Parabens, voce chegou aos 1000 cookies, ao infinito e alem!");
        } else if (cookieCounter > 10000) {
            txtPontos.setText(Integer.toString((ponto*5)+cookieCounter));
            jtxtMensagem.setText("Pare pessoa, você vai quebrar o seu mouse ainda!!");
        }
        
    }//GEN-LAST:event_btnCookieActionPerformed

    private void mbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnSalvarActionPerformed
        salvamento();
    }//GEN-LAST:event_mbtnSalvarActionPerformed

    private void mbtnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnCarregarActionPerformed
        try {
            carregar();
        } catch (IOException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mbtnCarregarActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        txtPontos.setText("0");
        jtxtMensagem.setText("");
    }//GEN-LAST:event_btnResetarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCookie;
    private javax.swing.JButton btnResetar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jtxtMensagem;
    private javax.swing.JMenuItem mbtnCarregar;
    private javax.swing.JMenuItem mbtnSalvar;
    private cookie.clicker.Painel painel1;
    private javax.swing.JTextField txtPontos;
    // End of variables declaration//GEN-END:variables
    
    public void salvamento(){
        try{
            FileWriter escritor = new FileWriter("src/arquivotxt/pontuacao.txt");   
            escritor.write(txtPontos.getText());
            escritor.close();
            JOptionPane.showMessageDialog(rootPane, "Arquivo salvo com sucesso");        
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possivel salvar");
        }
    }
    
    public void carregar() throws IOException{
        String arquvio = new String(Files.readAllBytes(Paths.get("src/arquivotxt/pontuacao.txt")));
        txtPontos.setText(arquvio);
    }

}
